# Generated by Django 4.2.15 on 2024-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaivariety',
            options={'verbose_name': 'Chai Variety', 'verbose_name_plural': 'Chai Variety'},
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='details',
            field=models.TextField(default='empty'),
        ),
    ]
