# Generated by Django 4.2.15 on 2024-09-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_alter_chaivariety_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivariety',
            old_name='details',
            new_name='description',
        ),
    ]
